name: Proves de API-REST a GitHub

on:
  push:
    branches:
      - main

jobs:
  una_tasca_automatica:
    runs-on: ubuntu-latest
    steps:
      - name: Mostra un missatge per consola
        run: echo "Funciona primera prova"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pip3 Flask
        run: pip3 install Flask
      - name: Executar app
        run: python3 api_calculadora.py &
      - name: Prova principal curl
        run: curl -i 127.0.0.1:5000/
      - name: Prova suma
        run: curl -i 127.0.0.1:5000/suma/4/8 | grep "resultat -> 12"
      - name: Prova resta
        run: curl -i 127.0.0.1:5000/resta/8/4
      - name: Prova multiplica
        run: curl -i 127.0.0.1:5000/multiplica/4/5
      - name: Prova divideix
        run: curl -i 127.0.0.1:5000/divideix/20/5
